[libraries]
compress            = { module = "org.apache.commons:commons-compress", version = "1.28.0" }
hash4j              = { module = "com.dynatrace.hash4j:hash4j", version = "0.27.0" }
jspecify            = { module = "org.jspecify:jspecify", version = "1.0.0" }
picocli             = { module = "info.picocli:picocli", version = "4.7.7" }
slf4j               = { module = "org.slf4j:slf4j-jdk14", version = "2.0.17" }

assertJ             = { module = "org.assertj:assertj-core", version = "3.27.6" }
unit                = { module = "org.junit.jupiter:junit-jupiter", version = "6.0.0" }
unitPlatform        = { module = "org.junit.platform:junit-platform-runner", version = "1.14.0" }

[bundles]
testUnit            = [ "assertJ", "jspecify", "unit", "unitPlatform" ]
